import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';
import { TextField } from '@mui/material';

export default function Home() {
  const [mail, setMail] = useState('Loading...');
  const [data, setData] = useState('Loading...');
  const [sev, setSev] = useState('Small');
  const URL = 'http://urepairfreejohn1-env.eba-we2tn3yk.us-east-2.elasticbeanstalk.com/equipment/1'
    
  // const [hasData, setHasData] = useState(false)

  const getData = async () => {
    console.log('getData\n');
    const res = await fetch(URL);
    const dataObject = await res.json();
    const str = JSON.stringify(dataObject);
    setData(str);
  };

  const postData = async () => {
    const requestOptions = {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: 'React PUT Request Example' })
    };
    const res = await fetch(URL, requestOptions);
  };

  const handleMailChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setMail(event.target.value);
  };
  const handleSevChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSev(event.target.value);
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <TextField
          id="standard-basic"
          label="EMail"
          value={mail}
          onChange={handleMailChange}
        />
        <TextField
          id="standard-basic"
          label="Severity"
          value={sev}
          onChange={handleSevChange}
        />
    {mail}
    {sev}
        {/* <button type="submit" onClick={()=>setData("pizza")}>Register Input</button> */}
      </main>
    </>
  );
}
