import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';
import  Form from './cmp/form'
import Staff from './cmp/staff'
import Nav from './cmp/nav'
import { Button } from '@mui/material';

export default function Home() {
  const [isStaff, setIsStaff] = useState(false);
  const URL = 'http://urepair-env.eba-hnfscrcj.us-east-2.elasticbeanstalk.com/issue'

  const handleStaffChange = () => setIsStaff(!isStaff);

  return (
    <>
      <Head>
        <title>URepair App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <Nav staff={isStaff} onStaffChange={handleStaffChange}/> */}
        <Button
          size="large"
          variant="contained"
          onClick={handleStaffChange}
        >
            {isStaff ? "User" : "Staff"} Login
        </Button>
        {isStaff ? <Staff /> : <Form />}
      </main>
    </>
  );
}
