import React, { useState } from 'react';
import { Button } from '@mui/material';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import './styles/App.css';
import Form from './cmp/form';
import SignIn from './cmp/signin';

const theme = createTheme({
  palette: {
    primary: {
      main: '#881c1c',
    },
  },
});

function App() {
  const [isStaff, setIsStaff] = useState(false);
  const handleStaffChange = () => setIsStaff(!isStaff);
  return (
    <>
      <head>
        <title>URepair App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider theme={theme}>
        <main className="main">
          {/* <Nav staff={isStaff} onStaffChange={handleStaffChange}/> */}
          <div className="nav">
            <Button
              size="large"
              variant="contained"
              onClick={handleStaffChange}
              className="staffLogin"
            >
              {isStaff ? 'User' : 'Staff'}
              {' '}
              Login
            </Button>
          </div>
          {isStaff ? <SignIn /> : <Form />}
        </main>
      </ThemeProvider>
    </>
  );
}

export default App;
