import React, { useState } from 'react';
import ReactDOM from 'react-dom/client';
import './styles/main.css';
import './styles/index.css';

// const [thing, setThing]  = useState("")

export default function Home() {
  const [data, setData] = useState("Loading...")
  //const [hasData, setHasData] = useState(false)

  const getData = async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/todos/1")
    const data = await res.json()
    setData(data.title)
  }
}

// @ts-ignore
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <>
      <header>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </header>
      <main className="main">
        <div className="description">
          <p>
            Get started by editing&nbsp;
            <code className="code">src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              {/* <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              /> */}
            </a>
          </div>
        </div>

        <div className="center">
          {/* <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          /> */}
          <div className="thirteen">
            {/* <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            /> */}
          </div>
        </div>

        <div className="grid">
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="grid"
            target="_blank"
            rel="noopener noreferrer"
          >
            {/* <h2 className={inter.className}> */}
              Docs <span>-&gt;</span>
            {/* </h2> */}
            {/* <p className={inter.className}> */}
              Find in-depth information about Next.js features and&nbsp;API.
            {/* </p> */}
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="card"
            target="_blank"
            rel="noopener noreferrer"
          >
            {/* <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p> */}
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="card"
            target="_blank"
            rel="noopener noreferrer"
          >
            {/* <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p> */}
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="card"
            target="_blank"
            rel="noopener noreferrer"
          >
            {/* <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p> */}
          </a>
        </div>
      </main>
    </>
);